apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "explorer.fullname" . }}-crypto3
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- (.Files.Glob "crypto-config/peerOrganizations/peersample.example.com/users/Admin@peersample.example.com/msp/keystore/5edee1d4488fe1341162ea2d9db6b148918bfd765e66f15897d136a1dc932309_sk").AsConfig | nindent 2 }}



